[package]
name = "clash-verge-logger"
version = "0.1.0"
edition = "2024"
authors = ["Tunglies"]
license = "GPL-3.0"

[features]
color = ["nu-ansi-term"]

[dependencies]
flexi_logger = "0.31.4"
log = "0.4.28"
nu-ansi-term = {version = "0.50.1", optional = true}
